# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stations.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0estations.proto\" \n\rreadRequestPB\x12\x0f\n\x07zipcode\x18\x01 \x01(\t\"!\n\x0ereadResponsePB\x12\x0f\n\x07zipcode\x18\x01 \x01(\t\"6\n\x12readResponseListPB\x12 \n\x07station\x18\x01 \x03(\x0b\x32\x0f.readResponsePB23\n\x08Stations\x12\'\n\x04Read\x12\x0e.readRequestPB\x1a\x0f.readResponsePBb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stations_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _READREQUESTPB._serialized_start=18
  _READREQUESTPB._serialized_end=50
  _READRESPONSEPB._serialized_start=52
  _READRESPONSEPB._serialized_end=85
  _READRESPONSELISTPB._serialized_start=87
  _READRESPONSELISTPB._serialized_end=141
  _STATIONS._serialized_start=143
  _STATIONS._serialized_end=194
# @@protoc_insertion_point(module_scope)
