# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stations.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0estations.proto\"\"\n\x0fStationsRequest\x12\x0f\n\x07zipcode\x18\x01 \x01(\t\"#\n\x10StationsResponse\x12\x0f\n\x07zipcode\x18\x01 \x01(\t\"4\n\x0eresponseListPB\x12\"\n\x07station\x18\x01 \x03(\x0b\x32\x11.StationsResponse27\n\x08Stations\x12+\n\x04Read\x12\x10.StationsRequest\x1a\x11.StationsResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stations_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATIONSREQUEST._serialized_start=18
  _STATIONSREQUEST._serialized_end=52
  _STATIONSRESPONSE._serialized_start=54
  _STATIONSRESPONSE._serialized_end=89
  _RESPONSELISTPB._serialized_start=91
  _RESPONSELISTPB._serialized_end=143
  _STATIONS._serialized_start=145
  _STATIONS._serialized_end=200
# @@protoc_insertion_point(module_scope)
