# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stations.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0estations.proto\"\xbe\x01\n\x10StationsResponse\x12\'\n\x1fgare_alias_libelle_noncontraint\x18\x01 \x01(\t\x12\x1a\n\x12\x63ommune_libellemin\x18\x02 \x01(\t\x12\x10\n\x08uic_code\x18\x03 \x01(\t\x12\x12\n\nadresse_cp\x18\x04 \x01(\t\x12\x1e\n\x16\x64\x65partement_libellemin\x18\x05 \x01(\t\x12\x1f\n\x17gare_regionsncf_libelle\x18\x06 \x01(\t2;\n\x08Stations\x12/\n\x07Station\x12\x11.StationsResponse\x1a\x11.StationsResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stations_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATIONSRESPONSE._serialized_start=19
  _STATIONSRESPONSE._serialized_end=209
  _STATIONS._serialized_start=211
  _STATIONS._serialized_end=270
# @@protoc_insertion_point(module_scope)
