# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import stations_pb2 as stations__pb2


class StationsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Station = channel.unary_unary(
                '/Stations/Station',
                request_serializer=stations__pb2.StationsResponse.SerializeToString,
                response_deserializer=stations__pb2.StationsResponse.FromString,
                )


class StationsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Station(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Station': grpc.unary_unary_rpc_method_handler(
                    servicer.Station,
                    request_deserializer=stations__pb2.StationsResponse.FromString,
                    response_serializer=stations__pb2.StationsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Stations', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Stations(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Station(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Stations/Station',
            stations__pb2.StationsResponse.SerializeToString,
            stations__pb2.StationsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
